In [11]:
from components.Taikyoku_loader import Taikyoku_loader
import os, sys
import numpy as np

np.set_printoptions(threshold=np.inf)

path = os.path.join(os.path.dirname(os.path.dirname(os.getcwd())), "dataset/Tenhou")
filename = "test.log"
loader = Taikyoku_loader(os.path.join(path, filename))
num = 3
loader.reset(num)
for i in range(len(loader.log[num-1])-1):
    loader.step_forward()

export = loader.export_info()

Action.CHI_top


In [12]:
from components.encoder import Encoder

encoder = Encoder(export)
print(encoder.exported_info['taikyoku_info']['remain_draw'])
print(encoder.encode()[:,:3])

29
[[1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 2.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 1.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 2.90e+01 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 3.09e+04 0.00e+00]
 [1.00e+00 2.99e+04 0.00e+00]
 [1.00e+00 5.90e+03 0.00e+00]
 [1.00e+00 3.33e+04 1.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 0.00e+00 0.00e+00]
 [1.00e