In [1]:
import numpy as np
from base_module import *

from pymahjong import *
from pymahjong import MahjongPyWrapper as pm
from pymahjong.myEnv_pymahjong import myMahjongEnv

env = myMahjongEnv()
obs, info = env.reset()
while not env.is_over():
    valid_actions = env.get_valid_actions()
    action = np.random.choice(valid_actions)
    obs, r, done, _, info = env.step(action_idx=action)

/data/satori_hdd4/Ren/envs/RL_uzumaki/lib/python3.10/site-packages/torch/cuda/__init__.py:619: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [2]:
collator = myCollator()
data = collator(info['obs_with_return'])

In [8]:
info['obs_with_return'][0]['self_action_mask']

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
print("tiles_features shape:",data['tiles_features'].shape)
print("oya:", data['info']['oya'].shape)
print("riichi:", data['info']['riichi_sticks'].shape)
print("action_list", data['action_list'].shape)
print("attention_mask", data['attention_mask'].shape)
print("self_action_mask", data['self_action_mask'].shape)
print("legal_action_mask", data['legal_action_mask'].shape)
print("Q_values", data['Q_values'].shape)

tiles_features shape: torch.Size([261, 35, 4, 9])
oya: torch.Size([261, 1])
riichi: torch.Size([261, 1])
action_list torch.Size([12, 128])
attention_mask torch.Size([12, 128])
self_action_mask torch.Size([12, 128])
legal_action_mask torch.Size([261, 47])
Q_values torch.Size([261])


In [9]:
data['self_action_mask']

tensor([0, 0, 0,  ..., 0, 0, 0], device='cuda:0')

In [2]:
collator = myCollator()
tiles_features, oya, riichi_sticks, action_lists, attention_masks, self_action_masks, legal_action_mask = collator.unpack(info['obs_with_return'])

In [3]:
print("tiles_features:", tiles_features.shape)


tiles_features: torch.Size([93, 35, 4, 9])


In [ ]:
aug_tiles_feature = collator.aug_tiles_features(tiles_features)
aug_action_list = collator.aug_action_list(action_lists, attention_masks)
aug_legal_action_mask = collator.aug_legal_action_mask(legal_action_mask)

In [11]:
print("legal_action_mask:", legal_action_mask[0][1])

legal_action_mask: [False False False  True False False False  True False  True  True False
 False  True False False False False False False False False False False
 False False False False False  True  True  True  True  True False False
 False False False False False False False False False False False]


In [12]:
aug_legal_action_mask[22]

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False,  True, False,  True,  True,
        False, False,  True, False, False, False, False, False, False,  True,
         True,  True,  True,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False])

In [13]:
def _expand_list(list_):
    return [item for item in list_ for _ in range(3)]

In [14]:
_expand_list([1,2,3,4,5])

[1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5]