# 1.验证模型结构

In [ ]:
import torch
import numpy as np
from base_module import *

from pymahjong import *
from pymahjong import MahjongPyWrapper as pm
from pymahjong.myEnv_pymahjong import myMahjongEnv

env = myMahjongEnv()
env.reset()


# 检测GPU是否可用
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

# 测试用输入
batch =  []
batch_size = 16
feature_channels = 35
feature_height = 4
feature_width = 9

action_space = 47

while len(batch) < batch_size:
    while not env.is_over():
        curr_pid = env.get_curr_player_id()
        valid_actions = env.get_valid_actions()
        action = np.random.choice(valid_actions)
        env.step(player_id=curr_pid, action=action)
    print(env.get_payoffs())
    for i in range(4):
        batch.append(env.get_observation_with_return(i))
    env.reset()
collator = myCollator()

In [ ]:
from base_module import *
import torch
import torch.nn as nn
import numpy as np
from transformers import GPT2Model, GPT2Config


# 检测GPU是否可用
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)
# 创建模型
config = GPT2Config(n_embd=512, n_layer=8, n_head=8, n_positions=128)
model = Policy_Network(config).to(device)
data = collator(batch)
model.eval()


In [ ]:

output = model.forward(**data)
print("action_logits:", output["action_logits"].shape)
print(output["action_logits"][0])
print("probs:", output["action_probs"][0])
# print("loss:", output["loss"])
print("action:", output["action"])


# 2.验证麻将环境

In [1]:
from pymahjong import *
from pymahjong import MahjongPyWrapper as pm
from pymahjong.myEnv_pymahjong import myMahjongEnv

env = myMahjongEnv()
env.reset()

In [ ]:
print(env.get_valid_actions())
print(env.legal_actions_mask_record)

In [ ]:
while not env.is_over():
    curr_pid = env.get_curr_player_id()
    valid_actions = env.get_valid_actions()
    action = np.random.choice(valid_actions)
    env.step(player_id=curr_pid, action=action)
print(env.get_payoffs())

#### 展示当前phase和合法动作列表

In [ ]:
phase, aviable_action = env._proceed()
print("phase:", phase)
for idx, action in enumerate(aviable_action):
    print(idx, action.to_string())

valid_action = env.get_valid_actions()
print("valid_action:", valid_action)

#### 执行动作

In [4]:
env.step(2, 0)

In [ ]:
for i in range(4):
    print("player", i, "hand:", env._get_hand_tiles(i))

In [ ]:
obs = env.get_observation(1)
print("tiles_features shape:", obs['tiles_features'].shape)
print("oya shape:", obs['info']['oya'].shape)
print("riichi_sticks shape:", obs['info']['riichi_sticks'].shape)
print("action_list shape:", obs['action_list'].shape)
print("action_list:", obs['action_list'])
print("self_action_mask shape:", obs['self_action_mask'].shape)
print("self_action_mask:", obs['self_action_mask'])
print("sum self_action_mask:", obs['self_action_mask'].sum())
print("attention_mask shape:", obs['attention_mask'].shape)
print("attention_mask:", obs['attention_mask'])
print("Q shape:", obs['Q_values'].shape)
print("Q:", obs['Q_values'])
print("legal_action_mask shape:", obs['legal_action_mask'].shape)
print("legal_action_mask:", obs['legal_action_mask'])

In [ ]:
for i in range(4):
    print("player", i, "fuuros:", env._get_fuuros(i))
    print("points:", env._get_points(i))

In [ ]:
obs['info']

# 3.使用模型来决策

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
import torch

# 使用第一个可用的 GPU，即设备 1
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")


In [ ]:
import torch
import numpy as np
from base_module import *

from pymahjong import *
from pymahjong import MahjongPyWrapper as pm
from pymahjong.myEnv_pymahjong import myMahjongEnv

env = myMahjongEnv()
env.reset()

config = GPT2Config(n_embd=512, n_layer=8, n_head=8, n_positions=128)
model = Policy_Network(config).to(device)
model.eval()

collator = myCollator()
for i in range(100):
    while not env.is_over():
        curr_pid = env.get_curr_player_id()
        obs = env.get_observation(curr_pid)
        input = {
        "tiles_features": torch.tensor(obs['tiles_features'], dtype=torch.float32).to(device),
        "oya": torch.tensor(obs['info']['oya'], dtype=torch.float32).unsqueeze(0).to(device),
        "riichi_sticks": torch.tensor(obs['info']['riichi_sticks'],dtype=torch.float32).unsqueeze(0).to(device),
        "action_list": torch.tensor(obs['action_list'],dtype=torch.long).unsqueeze(0).to(device),
        "attention_mask": torch.tensor(obs['attention_mask'],dtype=torch.long).unsqueeze(0).to(device),
        "legal_action_mask": torch.tensor(obs['legal_action_mask'], dtype=bool).to(device)
        }
        output = model.inference(**input)
        action = output["action"].item()
        env.step(player_id=curr_pid, action=action)
        # print("player:", curr_pid, "action:", action)
    print(env.get_payoffs())
    env.reset()



# print("action:", output["action"])

# 4. 开始训练

In [ ]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
import torch

# 使用第一个可用的 GPU，即设备 1
inference_device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
training_device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")

print("inference_device:", inference_device)
print("training_device:", training_device)

import numpy as np
from base_module import *

from pymahjong import *
from pymahjong import MahjongPyWrapper as pm
from pymahjong.myEnv_pymahjong import myMahjongEnv

env = myMahjongEnv()
env.reset()

config = GPT2Config(n_embd=512, n_layer=8, n_head=8, n_positions=128)
inference_model = Policy_Network(config).to(inference_device)
inference_model.eval()

training_model = Policy_Network(config).to(training_device)
training_model.load_state_dict(inference_model.state_dict())
training_model.train()

collator = myCollator(device=training_device)
optimizer = torch.optim.Adam(training_model.parameters(), lr=1e-4)

In [ ]:
epoch = 10
num_games = 10
for i in range(epoch): 
   # 生成10局对局数据
    dataset = []
    for i in range(num_games):
        while not env.is_over():
            curr_pid = env.get_curr_player_id()
            obs = env.get_observation(curr_pid)
            input = {
            "tiles_features": torch.tensor(obs['tiles_features'], dtype=torch.float32).to(inference_device),
            "oya": torch.tensor(obs['info']['oya'], dtype=torch.float32).unsqueeze(0).to(inference_device),
            "riichi_sticks": torch.tensor(obs['info']['riichi_sticks'],dtype=torch.float32).unsqueeze(0).to(inference_device),
            "action_list": torch.tensor(obs['action_list'],dtype=torch.long).unsqueeze(0).to(inference_device),
            "attention_mask": torch.tensor(obs['attention_mask'],dtype=torch.long).unsqueeze(0).to(inference_device),
            "legal_action_mask": torch.tensor(obs['legal_action_mask'], dtype=bool).to(inference_device)
            }
            output = inference_model.inference(**input)
            action = output["action"].item()
            env.step(player_id=curr_pid, action=action)
        for i in range(4):
            dataset.append(env.get_observation_with_return(i))
        print(env.get_payoffs())
        env.reset()

    # 从dataset中每次取出batch_size个数据
    batch_size = 4
    collator = myCollator()
    for i in range(0, len(dataset), batch_size):
        optimizer.zero_grad()
        batch = dataset[i:i+batch_size]
        data = collator(batch)
        # 移动数据到training_device
        for key in data.keys():
            if key == "info":
                for sub_key in data[key].keys():
                    data[key][sub_key] = data[key][sub_key].to(training_device)
            else:
                data[key] = data[key].to(training_device)
        output = training_model.forward(**data)
        loss = output["loss"]
        loss.backward()
        optimizer.step()
        print("loss:", loss.item())

    # 将training_model的参数复制到inference_model,并保存checkpoint
    inference_model.load_state_dict(training_model.state_dict())
    torch.save(inference_model.state_dict(), f"./checkpoints/epoch_{epoch}.pth")






In [ ]:
print("phase:", env.t.get_phase())
print("player:", env.get_curr_player_id())
print("legal actions:", env.get_valid_actions())
print("action", action)
action_container = env.act_container
nonzero_index = [i for i in range(len(action_container)) if action_container[i] != 0]
print("nonzero_index:", nonzero_index)

In [ ]:
env.step(3, 45)

# 5.检查环境bug

In [1]:
import numpy as np
from base_module import *

from pymahjong import *
from pymahjong import MahjongPyWrapper as pm
from pymahjong.myEnv_pymahjong import myMahjongEnv

env = myMahjongEnv()

flag = True
# for i in range(10000):
while flag:
    env.reset()
    while not env.is_over():
        curr_pid = env.get_curr_player_id()
        phase = env.t.get_phase()
        if phase < 4:
            aviable_action = env.t.get_self_actions()
        elif phase < 16:
            aviable_action = env.t.get_response_actions()


        ls = []
        for action in aviable_action:
            ls.append(action.action.name)
        set_ls = set(ls)
        if "Riichi" in set_ls:
            flag = False
            print("phase:", phase)
            print("aviable_action:", set_ls)
            break

        valid_actions = env.get_valid_actions()
        action = np.random.choice(valid_actions)
        env.step(player_id=curr_pid, action_idx=action)
    print(env.get_payoffs())






/opt/anaconda3/envs/RL/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[ 1500.  1500. -1500. -1500.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[-1000.  3000. -1000. -1000.]
[-1000.  3000. -1000. -1000.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[ 3000. -1000. -1000. -1000.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.

In [1]:
import numpy as np
from base_module import *

from pymahjong import *
from pymahjong import MahjongPyWrapper as pm
from pymahjong.myEnv_pymahjong import myMahjongEnv

env = myMahjongEnv()
env.reset()

/opt/anaconda3/envs/RL/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [9]:
print("phase:", env.t.get_phase())
print("curr_pid:", env.get_curr_player_id())
phase = env.t.get_phase()
if phase < 4:
    aviable_action = env.t.get_self_actions()
elif phase < 16:
    aviable_action = env.t.get_response_actions()
print("aviable_action:")
ls = []
for idx, action in enumerate(aviable_action):
    ls.append(action.to_string())
    print(idx, action.to_string())
    # print(action.action.name)

# print("aviable_action:", ls)

phase: 0
curr_pid: 0
aviable_action:
0 Discard 9m
1 Discard 3p
2 Discard 8s
3 Discard 2z
4 Discard 7z


In [10]:
env.get_valid_actions()

[33, 8, 11, 25, 28]

In [8]:
env.step(env.get_curr_player_id(), 3)

In [7]:
env.riichi_stage2

False

In [154]:
env.t.make_selection(7)
phase = env.t.get_phase()
if phase < 4:
    aviable_action = env.t.get_self_actions()
elif phase < 16:
    aviable_action = env.t.get_response_actions()
print("after phase:", phase)
print("after aviable_action:")
for idx, action in enumerate(aviable_action):
    print(idx, action.to_string())


after phase: 4
after aviable_action:
0 Pass


In [178]:
env.t.make_selection(0)
phase = env.t.get_phase()
if phase < 4:
    aviable_action = env.t.get_self_actions()
elif phase < 16:
    aviable_action = env.t.get_response_actions()
print("after phase:", phase)
print("after aviable_action:")
for idx, action in enumerate(aviable_action):
    print(idx, action.to_string())

after phase: 16
after aviable_action:
0 Pass


In [11]:
print(phase)
print(env.t.to_string())

0
Yama: 3m 3z 1m 6z 3p 4s 5z 4m 7p 2z 3m 6z 7s 4p (Wanpai)| 8s 3s 8s 7m 5s 5z 3z 8m 3z 7p 0m 5z 8p 6m 3m 2p 1z 1p 7m 4p 6s 4z 5p 4s 5p 9s 5m 2p 3s 3s 5m 6m 4m 6s 6p 3p 4m 1p 8m 6p 3s 5m 
Dora Indicator(s):4s 
Remaining tiles: 42
Player 0: 
Pt: 25000
Wind: South
Hand: 9m 3p 8s 7z 2z 
Calls: 6p7p(8p) 2m2m(2m) 1m(1m)1m 
River: 6m2h 9m6h 3z10h 0p14h 8m16h 8p19h 5s23h- 6s26h 4z30h- 
Riichi: No
Menzen: No
Player 1: 
Pt: 25000
Wind: West
Hand: 6m 2p 8p 1s 1s 2s 4s 6s 7s 2z 2z 5z 7z 
River: 7s3h 7p7h 1z11h 2m15h- 3m17 7m20h 1p27h 
Riichi: No
Menzen: Yes
Player 2: 
Pt: 25000
Wind: North
Hand: 7m 8m 2p 9p 9p 8s 7z 
Calls: 0s(5s)5s 4z(4z)4z 
River: 7s4h 6p8h 7z12 1m18h- 4s21h 6z24h 2s28h 6z31h 
Riichi: No
Menzen: No
Player 3: 
Pt: 25000
Wind: East
Hand: 9m 9m 4p 4p 5p 9p 9p 1s 1s 2s 2s 9s 9s 
River: 1z1h 8p5h- 2m9h 1p13h 9s22h 1z25h 3p29h 4m32h 
Riichi: No
Menzen: Yes

Oya player 3
Honba: 0
Kyoutaku: 0



In [205]:
env.get_payoffs()

array([ -700.,  2700., -1300.,  -700.], dtype=float32)